### ISSUE TITLE
Exiting Python doesn't shut down spawned APL interpreter

### ISSUE THREAD

**Issue by jayfoad** [marinuso/pynapl#3]
On Linux, if I instantiate the Python class APL and then exit the Python interpreter, a Dyalog APL interpreter is left running in the background:

```
$ pidof dyalog # no dyalog processes
$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pynapl import APL
>>> apl = APL.APL()
>>> quit()
$ pidof dyalog # one dyalog process still running
10464
```

**Comment by marinuso** [comment]
Is it doing this consistently? I can't reproduce it. 

```
[marinus@marinus-laptop:~/pybridge$ pidof dyalog
17833
marinus@marinus-laptop:~/pybridge$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pynapl import APL
>>> apl = APL.APL()
>>> apl.eval("⎕NA'I libc.so.6|getpid'")
'getpid'
>>> apl.eval("getpid")
21960
>>> quit()
marinus@marinus-laptop:~/pybridge$ pidof dyalog
17833
marinus@marinus-laptop:~/pybridge$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pynapl import APL
>>> apl = APL.APL()
>>> quit()
marinus@marinus-laptop:~/pybridge$ pidof dyalog
17833
marinus@marinus-laptop:~/pybridge$ 
```

**Comment by jayfoad** [comment]
Yes it's consistent. But I've just noticed that it's only a problem with interpreter version 17.0:
```
>>> apl.eval("'.'⎕wg'APLVersion'")
['Linux-64', '17.0.30771.0', 'S', 'Development']
```
So maybe it's an interpreter bug.

**Comment by marinuso** [comment]
That's still weird. The APL script that `RunDyalog.py` passes in is supposed to run `)OFF` at the end, and in case the script has crashed, the destructor of the APL object also sends `SIGTERM` to the Dyalog interpreter. 

If you do `apl.stop()` by hand, does that stop it?

**Comment by jayfoad** [comment]
> If you do apl.stop() by hand, does that stop it?

No. The APL interpreter is still running. It's in the ⎕DL÷4 in Stop, so maybe it has got stuck in some infinite loop calling Stop over and over again?

**Comment by jayfoad** [comment]
Aha! It is an interpreter bug (Mantis 14658) where the interpreter can get stuck running the same destructor infinitely many times. Sorry for the noise.
